/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppApiGuideRouteImport } from './routes/app.api-guide'
import { Route as AppPortalsRouteImport } from './routes/app.portals'
import { Route as AppSessionsRouteImport } from './routes/app.sessions'
import { Route as AppAdminAuditRouteImport } from './routes/app.admin.audit'
import { Route as AppAdminClientsRouteImport } from './routes/app.admin.clients'
import { Route as AppAdminPeopleRouteImport } from './routes/app.admin.people'
import { Route as AppAdminPortalsRouteImport } from './routes/app.admin.portals'
import { Route as AppAdminTeamsRouteImport } from './routes/app.admin.teams'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApiGuideRoute = AppApiGuideRouteImport.update({
  id: '/api-guide',
  path: '/api-guide',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalsRoute = AppPortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminClientsRoute = AppAdminClientsRouteImport.update({
  id: '/admin/clients',
  path: '/admin/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPeopleRoute = AppAdminPeopleRouteImport.update({
  id: '/admin/people',
  path: '/admin/people',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPortalsRoute = AppAdminPortalsRouteImport.update({
  id: '/admin/portals',
  path: '/admin/portals',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTeamsRoute = AppAdminTeamsRouteImport.update({
  id: '/admin/teams',
  path: '/admin/teams',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/api-guide': typeof AppApiGuideRoute
  '/app/portals': typeof AppPortalsRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/clients': typeof AppAdminClientsRoute
  '/app/admin/people': typeof AppAdminPeopleRoute
  '/app/admin/portals': typeof AppAdminPortalsRoute
  '/app/admin/teams': typeof AppAdminTeamsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/api-guide': typeof AppApiGuideRoute
  '/app/portals': typeof AppPortalsRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/clients': typeof AppAdminClientsRoute
  '/app/admin/people': typeof AppAdminPeopleRoute
  '/app/admin/portals': typeof AppAdminPortalsRoute
  '/app/admin/teams': typeof AppAdminTeamsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/api-guide': typeof AppApiGuideRoute
  '/app/portals': typeof AppPortalsRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/clients': typeof AppAdminClientsRoute
  '/app/admin/people': typeof AppAdminPeopleRoute
  '/app/admin/portals': typeof AppAdminPortalsRoute
  '/app/admin/teams': typeof AppAdminTeamsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/api-guide'
    | '/app/portals'
    | '/app/sessions'
    | '/app/'
    | '/app/admin/audit'
    | '/app/admin/clients'
    | '/app/admin/people'
    | '/app/admin/portals'
    | '/app/admin/teams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/api-guide'
    | '/app/portals'
    | '/app/sessions'
    | '/app'
    | '/app/admin/audit'
    | '/app/admin/clients'
    | '/app/admin/people'
    | '/app/admin/portals'
    | '/app/admin/teams'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/api-guide'
    | '/app/portals'
    | '/app/sessions'
    | '/app/'
    | '/app/admin/audit'
    | '/app/admin/clients'
    | '/app/admin/people'
    | '/app/admin/portals'
    | '/app/admin/teams'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/api-guide': {
      id: '/app/api-guide'
      path: '/api-guide'
      fullPath: '/app/api-guide'
      preLoaderRoute: typeof AppApiGuideRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portals': {
      id: '/app/portals'
      path: '/portals'
      fullPath: '/app/portals'
      preLoaderRoute: typeof AppPortalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sessions': {
      id: '/app/sessions'
      path: '/sessions'
      fullPath: '/app/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/audit': {
      id: '/app/admin/audit'
      path: '/admin/audit'
      fullPath: '/app/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/clients': {
      id: '/app/admin/clients'
      path: '/admin/clients'
      fullPath: '/app/admin/clients'
      preLoaderRoute: typeof AppAdminClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/people': {
      id: '/app/admin/people'
      path: '/admin/people'
      fullPath: '/app/admin/people'
      preLoaderRoute: typeof AppAdminPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/portals': {
      id: '/app/admin/portals'
      path: '/admin/portals'
      fullPath: '/app/admin/portals'
      preLoaderRoute: typeof AppAdminPortalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/teams': {
      id: '/app/admin/teams'
      path: '/admin/teams'
      fullPath: '/app/admin/teams'
      preLoaderRoute: typeof AppAdminTeamsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApiGuideRoute: typeof AppApiGuideRoute
  AppPortalsRoute: typeof AppPortalsRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminClientsRoute: typeof AppAdminClientsRoute
  AppAdminPeopleRoute: typeof AppAdminPeopleRoute
  AppAdminPortalsRoute: typeof AppAdminPortalsRoute
  AppAdminTeamsRoute: typeof AppAdminTeamsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApiGuideRoute: AppApiGuideRoute,
  AppPortalsRoute: AppPortalsRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminClientsRoute: AppAdminClientsRoute,
  AppAdminPeopleRoute: AppAdminPeopleRoute,
  AppAdminPortalsRoute: AppAdminPortalsRoute,
  AppAdminTeamsRoute: AppAdminTeamsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
